package com.tiv.ocpapp.model_dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.tiv.ocpapp.model_dao.Answer;
import com.tiv.ocpapp.model_dao.Question;

import com.tiv.ocpapp.model_dao.AnswerDao;
import com.tiv.ocpapp.model_dao.QuestionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig answerDaoConfig;
    private final DaoConfig questionDaoConfig;

    private final AnswerDao answerDao;
    private final QuestionDao questionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        answerDaoConfig = daoConfigMap.get(AnswerDao.class).clone();
        answerDaoConfig.initIdentityScope(type);

        questionDaoConfig = daoConfigMap.get(QuestionDao.class).clone();
        questionDaoConfig.initIdentityScope(type);

        answerDao = new AnswerDao(answerDaoConfig, this);
        questionDao = new QuestionDao(questionDaoConfig, this);

        registerDao(Answer.class, answerDao);
        registerDao(Question.class, questionDao);
    }
    
    public void clear() {
        answerDaoConfig.getIdentityScope().clear();
        questionDaoConfig.getIdentityScope().clear();
    }

    public AnswerDao getAnswerDao() {
        return answerDao;
    }

    public QuestionDao getQuestionDao() {
        return questionDao;
    }

}
